name: Continuous Integration
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Format
        run: cargo fmt --check

      - name: Clippy
        run: cargo clippy -- -D warnings

      - name: Test
        run: cargo test

      - name: Test E2E
        run: |
          echo "Simple Transactions"
          cargo r -- ./fixtures/sample_01.csv > sample_01.out.csv && diff ./fixtures/sample_01.out.csv sample_01.out.csv
          echo "Complex Transactions"
          cargo r -- ./fixtures/sample_02.csv > sample_02.out.csv && diff ./fixtures/sample_02.out.csv sample_02.out.csv
          echo "Chargeback Support"
          cargo r -- ./fixtures/sample_03.csv > sample_03.out.csv && diff ./fixtures/sample_03.out.csv sample_03.out.csv
          echo "Unknown Transaction Types"
          cargo r -- ./fixtures/sample_04.csv > sample_04.out.csv && diff ./fixtures/sample_04.out.csv sample_04.out.csv
          echo "Disallow Duplicate Transactions"
          cargo r -- ./fixtures/sample_05.csv > sample_05.out.csv && diff ./fixtures/sample_05.out.csv sample_05.out.csv
